### ISSUE TITLE
PtoG getting rsync errors on some fonts

### ISSUE THREAD

**Issue by highlightshadow** [NoSloppy/SoundFontNamingConverter#2]
[ptog.log](https://github.com/NoSloppy/SoundFontNamingConverter/files/7621375/ptog.log)

When converting some proffie fonts to golden harvest getting rsync errors:
rsync: change_dir#3 "/mnt/e/Saber Stuff/Tools/SoundFontNameConverter//./Converted_to_GoldenHarvest/Proffie/Bandit/Proffie/Bandit" failed: No such file or directory (2)
Full log attached. The font is "Bandit" from Kyberphonic
![Screenshot 2021-11-29 215354](https://user-images.githubusercontent.com/68070842/143948862-b9e248a2-4ff7-45e0-a5a6-2f1258eade77.png)

**Comment by NoSloppy** [comment]
Sounds like you didn't enter the correct path for the font maybe?
Your responses to the questions based on the path shown in the image above would be:
```
PtoG
1
y
Proffie/Bandit
1
```

**Comment by highlightshadow** [comment]
That's why I included the log. I did enter right path
Tried it with multi font option
It converted all except 3 which all had same error
I reran with just this font and it still produced same error

**Comment by NoSloppy** [comment]
Okay, thanks . Can you run it again and use option 1 for the detailed conversion? I have the same font and just ran it fine. You're on windows, yes? I'll double check the convert.sh file but it should be the same thing as the Mac .command file.

**Comment by highlightshadow** [comment]
I'm using the linux shell in windows (so running bash ./convert.sh
[ptog_1.log](https://github.com/NoSloppy/SoundFontNamingConverter/files/7624331/ptog_1.log)

**Comment by highlightshadow** [comment]
```
Converting Proffie/Bandit/endlb/endlb.wav to ./Converted_to_GoldenHarvest/Proffie/Bandit/Proffie/Bandit/save.wav
rsync: change_dir#3 "/mnt/e/Saber Stuff/Tools/SoundFontNameConverter//./Converted_to_GoldenHarvest/Proffie/Bandit/Proffie/Bandit" failed: No such file or directory (2)
rsync error: errors selecting input/output files, dirs (code 3) at main.c(720) [Receiver=3.1.3]

```
Looks like it's randomly adding an additional set of paths for the endlb.wav file

**Comment by NoSloppy** [comment]
Could you try it now?
Not sure why endlb was supposed to make save.wavs....

**Comment by highlightshadow** [comment]
Yep -- tried re-converting the font that was giving errors before and now is clean
Also looks like the numbering is better too -- i noticed sometimes it continued the file numbering rather than resetting each
