### ISSUE TITLE
PtoG misnames lockup sounds as lockup instead of lock

### ISSUE THREAD

**Issue by highlightshadow** [NoSloppy/SoundFontNamingConverter#3]
When GH3 detects a GH3 native font (which it seems to be doing from a script converted font) it seems to all work except lockups
Basically debugging this with Frederic (Sabertec) we've noticed that the lockup files are getting named lockup1.wav, lockup2.wav etc
For GH3 naming it should be **lock1.wav and lock2.wav etc**

Only lockup1.wav works if the font is detected as CFX native (which GH3 can interpret) but the script is doing a perfect job on the PtoG function but just needs the name of lockup changing.

Think this might be a regression or something --- checking through my fonts -- earlier fonts i used 2.5 against seem ok ... just the fonts i've converted since i downloaded 2.6. So seems to be new / retroduced bug

**Comment by NoSloppy** [comment]
I have never used GH actually, so blindly writing it based on someone else's input.
Easy fix, thanks for the heads up!
Done.
