### ISSUE TITLE
Error in rsync command on Mac

### ISSUE THREAD

**Issue by highlightshadow** [NoSloppy/SoundFontNamingConverter#5]
Not my issue but reported to me:
Running this new version on my Mac, it gave errors: "Converting font/clash1.wav to ./Converted_to_GoldenHarvest/font/clash1.wav
rsync: -Ab: unknown option" 
User modifed the script to use the lowercase "-ab", which worked.

**Comment by NoSloppy** [comment]
They're not the same thing, but it works either way for purposes here I suppose. 
Running Zsh shell might be the issue, but the script should invoke bash, so not really sure what's going on there.
