### ISSUE TITLE
Enhancement for Xeno v2

### ISSUE THREAD

**Issue by highlightshadow** [NoSloppy/SoundFontNamingConverter#6]
In an upcoming firmware version Xeno will get accent swing support.
Can you add that to the script now in anticipation

Naming will be swing (1).wav (space between swing and (x) number like the rest).
Thanks

**Comment by NoSloppy** [comment]
With parentheses like that?

**Comment by highlightshadow** [comment]
Yeah -- 
swing (1).wav
swing (2).wav 
etc
Same as the rest of the naming convention .... no rush on this ... it's still a feature in development but it is coming 
Just saves re-converting a load of fonts in the future

**Comment by NoSloppy** [comment]
Done. Thanks.
