### ISSUE TITLE
Xeno supports preon so can be included

### ISSUE THREAD

**Issue by highlightshadow** [NoSloppy/SoundFontNamingConverter#7]
Xeno board already supports preon so you can add support for that.
Seems the way Xeno is structured you create a subfolder called "preon"
Then the files in there are preon1.wav, preon2.wav etc
![xeno1](https://user-images.githubusercontent.com/68070842/151632281-8b8f082f-3134-4d8c-91ed-12ad8adb1b72.png)

**Comment by NoSloppy** [comment]
I did, but left an oops. Fixed now, thanks.
