### ISSUE TITLE
C to P a bit broken

### ISSUE THREAD

**Issue by highlightshadow** [NoSloppy/SoundFontNamingConverter#8]
Few issues with CtoP (and likely similar CtoX/CtoG)

- Only have 16 clash but produced 20 clsh files
- clsh17-20 sound like swing sounds 
- 
- drag01 is right but drag02 - drag08 are not drag sounds (think they're meant to be enddrag possibly)
- 
- It's put a lot of files into lock dir but none are lockups ... that's in the base folder as lock01.wav (which is right)
- 
- startdrag and startlock are not converted to bgndrag and bgnlock
- 
- poweronf.wav got converted to out5.wav <<< poweronf.wav == begin force (not sure if proffie has that)
- 
- Missed the tracks content
[conv C_to_P.txt](https://github.com/NoSloppy/SoundFontNamingConverter/files/8179403/conv.C_to_P.txt)
![cfx_source](https://user-images.githubusercontent.com/68070842/156609590-41b519b1-c2df-4a98-a05f-13f1a1f17449.png)

**Comment by NoSloppy** [comment]
Thanks. Please try now..
Your bullet points 1-4 were due to trying to anticipate users might have capital letters starting their sounds. Can't help everyone I guess.
Last point, Proffie has no force poweron sound - poweronf gets made into a regular out.wav.

**Comment by highlightshadow** [comment]
Doesn't look like you've comitted the change to the hub... file age still showing from 2 months ago

**Comment by NoSloppy** [comment]
Please test off this branch:
https://tinyurl.com/yb9vyglt

**Comment by highlightshadow** [comment]
Ahh sorry :)

Looks like lockup and humM1 didn't get picked up even though they're listed at the top:

```
CFX/Six_Claws/humM1.wav
CFX/Six_Claws/lockup.wav

No match found, ignoring file CFX/Six_Claws/humM1.wav
No match found, ignoring file CFX/Six_Claws/lockup.wav
```

**Comment by highlightshadow** [comment]
While it relocated the tracks it spat out a message implying it didn't
```
No match found, ignoring file CFX/Six_Claws/tracks/track1.wav
No match found, ignoring file CFX/Six_Claws/tracks/track2.wav
No match found, ignoring file CFX/Six_Claws/tracks/track3.wav/!(tracks)
```

**Comment by NoSloppy** [comment]
Yeah let me iron a few things out.

**Comment by highlightshadow** [comment]
No worries

**Comment by NoSloppy** [comment]
Ok . Main branch updated to 2.7 . Please test anything you can. I did, but with the same test fonts. Want to make sure I caught all the things (well, mostly)

**Comment by highlightshadow** [comment]
Awesome --- will this brach also affect CtoX and CtoG which i believe had similar issues

**Comment by highlightshadow** [comment]
Tested on the same 2 fonts as before -- looks good to me now checking all the folders and the core files all there now 
Great job

**Comment by NoSloppy** [comment]
> 

All conversions were updated
