### ISSUE TITLE
Extra character on line 1

### ISSUE THREAD

**Issue by highlightshadow** [NoSloppy/SoundFontNamingConverter#9]
Line 1 has a z at the beginning.
Shouldnt be there

**Comment by NoSloppy** [comment]
Not sure where that came from. 
Does it work on Windows without it? Maybe it was a PowerShell thing at some point....or just a typo when hitting shift.
If you can confirm it works without it, I'll remove it. Thanks.

**Comment by highlightshadow** [comment]
Yeah -- basically you get an error on windows that it can't find z#!/bin/sh 
Without the z it works cleanly.
So it's just a typo :)

**Comment by NoSloppy** [comment]
Done. Thanks.
